version: "3.7"

networks:
  web:
    name: web
  app:
    name: app
  mon:
    name: mon

services:
  # Reverse proxy
  reverse-proxy:
    image: traefik
    container_name: "reverse-proxy"
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    ports:
      - "5000:80"   # HTTP port
      - "5001:8080" # Web UI (enabled by --api.insecure=true)
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
      - app
      - mon

  # Demo web server
  web-server:
    build: "./web-server"
    image: "nginx:alpine"
    container_name: "web-server"
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-server.rule=Path(`/`)"
      - "traefik.docker.network=app"

  # Dashboards for monitoring metric analytics
  grafana:
    build: "./grafana"
    image: "grafana/grafana-arm32v7-linux"
    container_name: "grafana"
    ports:
      - "9000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_REPORTING_ENABLED=false
    restart: unless-stopped
    networks:
      - mon
    depends_on:
      - prometheus

  # Monitoring system and time series database
  prometheus:
    build: "./prometheus"
    image: "prom/prometheus"
    container_name: "prometheus"
    ports:
      - "9001:9090"
    restart: unless-stopped
    networks:
      - mon
    depends_on:
      - node-exporter
      - cadvisor

  # Exporter for machine metrics
  node-exporter:
    image: "prom/node-exporter"
    container_name: "node-exporter"
    ports:
      - "9002:9100"
    #network_mode: "host" # For real network monitoring
    pid: "host"
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
     #- "--web.listen-address=:9002"
    restart: unless-stopped
    networks:
      - mon

  # Analyzes resource usage and performance characteristics of running containers
  cadvisor:
    image: "budry/cadvisor-arm"
    container_name: "cadvisor"
    ports:
      - "9003:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only"
      - "--disable_metrics=disk,udp"
    restart: unless-stopped
    networks:
      - mon
