version: "3.8"

volumes:
  portainer:

networks:
  web:
    name: web
  app:
    name: app
  mon:
    name: mon

services:
  # Reverse proxy
  reverse-proxy:
    image: traefik
    container_name: "reverse-proxy"
    command:
      - --global.sendAnonymousUsage=false
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.defaultRule=HostRegexp(`{{ index .Labels "com.docker.compose.service" }}.{domain:.+}`)
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns
      - --certificatesresolvers.letsencrypt.acme.email=${DUCKDNS_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/acme.json
      - --entrypoints.http.address=:80
      - --entrypoints.http-pub.address=:8080
      - --entrypoints.http-pub.http.tls=true
      - --entrypoints.http-pub.http.tls.certresolver=letsencrypt
      - --entrypoints.http-pub.http.tls.domains[0].main=${DOMAIN_PUBLIC}
      - --entrypoints.http-pub.http.tls.domains[0].sans=*.${DOMAIN_PUBLIC}
    ports:
      - "80:80"     # HTTP internal port
      - "8080:8080" # HTTP public port
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/acme.json:/etc/acme.json
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    networks:
      - web
      - app
      - mon
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=HostRegexp(`traefik.{domain:.+}`)"
      - "traefik.http.routers.traefik.entrypoints=http"

  # Demo web server
  web-server:
    build: "./web-server"
    image: "web-server"
    container_name: "web-server"
    restart: unless-stopped
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app"
      - "traefik.http.routers.web-server.rule=Path(`/`)"
      - "traefik.http.routers.web-server.entrypoints=http"

  # Container management
  portainer:
    image: portainer/portainer:alpine
    container_name: "portainer"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - mon
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mon"
      - "traefik.http.routers.portainer.entrypoints=http"
