version: "3.8"

networks:
  mon:
    name: mon

services:
  # Dashboards for monitoring metric analytics
  grafana:
    build: "./grafana"
    image: "grafana/grafana-arm32v7-linux"
    container_name: "grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_REPORTING_ENABLED=false
    restart: unless-stopped
    networks:
      - mon
    depends_on:
      - prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mon"
      - "traefik.http.routers.grafana.entrypoints=http"

  # Monitoring system and time series database
  prometheus:
    build: "./prometheus"
    image: "prom/prometheus"
    container_name: "prometheus"
    restart: unless-stopped
    networks:
      - mon
    depends_on:
      - node-exporter
      - cadvisor
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mon"
      - "traefik.http.routers.prometheus.entrypoints=http"

  # Exporter for machine metrics
  node-exporter:
    image: "prom/node-exporter"
    container_name: "node-exporter"
    #network_mode: "host" # For real network monitoring
    pid: "host"
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
     #- "--web.listen-address=:9002"
    restart: unless-stopped
    networks:
      - mon
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mon"
      - "traefik.http.routers.node-exporter.entrypoints=http"

  # Analyzes resource usage and performance characteristics of running containers
  cadvisor:
    image: "zcube/cadvisor"
    container_name: "cadvisor"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only"
      - "--disable_metrics=disk,udp"
    restart: unless-stopped
    networks:
      - mon
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mon"
      - "traefik.http.routers.cadvisor.entrypoints=http"
