version: "3.8"

networks:
  app:
    external:
      name: app

services:
  file-server:
    build: ./file-server
    image: "file-server"
    container_name: "file-server"
    restart: unless-stopped
    volumes:
      - ${ROOT}:/usr/share/nginx/html
    networks:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app"
      - "traefik.http.routers.file-server.entrypoints=http"

  samba:
    image: dperson/samba
    container_name: "samba"
    command: "-p"
    environment:
      - SHARE=share;/share;yes;no;yes
      - USERID=${PUID}
      - GROUPID=${PGID}
      - RECYCLE=false
    volumes:
      - ${ROOT}:/share
    ports:
      - "139:139"
      - "445:445"
    restart: unless-stopped
